name: Judgement-of-the-Sun
main: com.gmail.kvkkuo.JotS.JotS
version: 1.0
api-version: 1.13
commands:
   class:
      description: Modify and customize a player's class.
      usage: /class
      permission: JotS.class
      permission-message: You don't have permission.
   boss:
      description: Spawn JotS bosses.
      usage: /boss
      permission: JotS.boss
      permission-message: You don't have permission.